# Generated by Django 3.2.13 on 2022-11-25 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('user_country', models.CharField(blank=True, max_length=50, null=True)),
                ('user_city', models.CharField(blank=True, max_length=50, null=True)),
                ('user_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user_company', models.CharField(blank=True, max_length=50, null=True)),
                ('created_user', models.DateTimeField(auto_now_add=True, verbose_name='Kullanıcı oluşturma Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'ordering': ['-created_user'],
            },
        ),
        migrations.CreateModel(
            name='FaturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(blank=True, max_length=50, null=True)),
                ('fatura_tutar', models.CharField(blank=True, max_length=50, null=True)),
                ('fatura_durum', models.CharField(blank=True, max_length=50, null=True)),
                ('created_fatura', models.DateTimeField(auto_now_add=True, verbose_name='Fatura oluşturma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fatura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Fatura',
                'ordering': ['-created_fatura'],
            },
        ),
    ]
